### ISSUE TITLE
Edit the CSS of project card

### ISSUE THREAD

**Issue by its-me-Harsh-Anand** [its-me-Harsh-Anand/portfolio-and-blog#1]
- Read the setup part for Getting Started.
- Change the page `/pages/projects.js`
    - Component for the same is in `/component/ProjectCard.js`
    - CSS file for the same is in `/styles/projectCard.module.css`
- Link to hosted page for change is [here](https://learnwithharsh.me/projects)

**Comment by Rounak-28** [comment]
@its-me-Harsh-Anand I can work in this

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand I can work in this

For any help, ping me

**Comment by Nainish-Rai** [comment]
hey, I want to contribute, Please assign so that i can start working on it.

**Comment by amansingh1373** [comment]
@its-me-Harsh-Anand  i can work on this kindly assign me this task

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand i can work on this kindly assign me this task

Sure, if you get any problem, ping me

**Comment by amansingh1373** [comment]
@its-me-Harsh-Anand i have made some changes in the cards kindly take a look at it
![cardschanged](https://user-images.githubusercontent.com/67228126/194146668-f56bd8b5-4bbf-4d37-8e7e-6a66333a8dc6.png)

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand i have made some changes in the cards kindly take a look at it ![cardschanged](https://user-images.githubusercontent.com/67228126/194146668-f56bd8b5-4bbf-4d37-8e7e-6a66333a8dc6.png)

That's awesome... but please check mobile view too

**Comment by its-me-Harsh-Anand** [comment]
Pull request merged
